package com.mcash.client.core.models.events

data class EventEntity(
    val booked: String,
    val creation_datetime: String,
    val event_date: String,
    val event_desc: String,
    val event_free_paid: String,
    val event_lat: String,
    val event_location: String,
    val event_long: String,
    val event_pic: List<String>,
    val event_title: String,
    val event_type: String,
    val first_name: String,
    val from_time: String,
    val id: String,
    val last_name: String,
    val member: String,
    val my_booked: String,
    val post_at: String,
    val profile_pic: List<String>,
    val rating: Any,
    val regular_event_price: String,
    val regular_no_of_participants: String,
    val status: String,
    val to_time: String,
    val user_id: String,
    val user_name: String,
    val currency: String? = "",
    val prefix: String? = "",
    val symbol_decimal: String? = "",
    val symbol_hex: String? = "",
    val vip_event_price: String,
    val vip_no_of_participants: String,
)